baseURL: https://jbirdsucks.com
languageCode: en-US
title: Just kidding, Jbird Rules!
disableKinds:
- section
- taxonomy
- RSS
- sitemap
disableHugoGeneratorInject: true
relativeURLs: true
uglyURLs: true
copyright: '&copy;2025 Jbirdsucks.com'
services:
  googleAnalytics:
    ID: ''
params:
  author: Ryan Roth
  description: Website made for and dedicated to Jbird.
  licensed: false
  favicon: favicon.ico
  visual:
    image:
      enable: false
      file: images/background.jpg
      position: center center
    video:
      enable: true
      mute: true
      file: videos/j-roll.mp4
  links:
  - list1:
      heading: Connect
      link:
      - text: Blog
        url: '#'
        new_tab: true
      - text: Email
        url: '#'
        new_tab: false
      - text: Newsletter
        url: '#'
  - list2:
      heading: Social
      link:
      - text: Twitter
        url: '#'
      - text: Instagram
        url: '#'
      - text: Dribbble
        url: '#'
  - list3:
      heading: Network
      link:
      - text: Link One
        url: '#'
      - text: Link Two
        url: '#'
      - text: Link Three
        url: '#'
server:
  headers:
  - for: /**
    values:
      Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
        https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src
        https://www.youtube.com/embed/; img-src 'self' https://dummyimage.com
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
