baseURL: https://jbirdsucks.com
languageCode: en-US
title: jbirdsucks.com
disableKinds:
- section
- taxonomy
- RSS
- sitemap
disableHugoGeneratorInject: true
relativeURLs: true
uglyURLs: true
copyright: '&copy;2025 Jbirdsucks.com'
markup:
  goldmark:
    renderer:
      unsafe: true
services:
  googleAnalytics:
    ID: ''
params:
  author: Ryan Roth
  description: Website dedicated to Jbird.
  licensed: false
  favicon: favicon.ico
  visual:
    image:
      enable: false
      file: images/background.jpg
      position: center center
    video:
      enable: true
      mute: true
      file: videos/j-roll.mp4
  #links:
  #- list1:
  #    heading: Connect
  #    link:
  #    - text: Blog
  #      url: '#'
  #      new_tab: true
  #    - text: Email
  #      url: '#'
  #      new_tab: false
  #    - text: Newsletter
  #      url: '#'
server:
  headers:
  - for: /**
    values:
      Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'
        https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; frame-src
        https://www.youtube.com/embed/; img-src 'self' https://dummyimage.com
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
